Attempt to stop tests failing occasionally on travis due to screenlock
Travis often fails tests with the following error:

> java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong.

It seems that this is due to the keypad locking if the emulator starts slowly.
Hopefully this commit will fix the problem.