Force sudo on travis
This will allow more disk space, so that the android emulator can successfully
be created.  This counters the error:

	Error: No space left on device
	Error: AVD not created.