Updated target version
Updated to avoid lint error, although not entirely required right now, since only updates after Nov 1, 2019 need to be on SDK 28, as per: https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

Example lint error:
> Error: Not targeting the latest versions of Android; compatibility modes apply.